#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Mar 10 00:43:55 JST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto bc7896355b3d4b4caaf88166cc137be7 --incr --debug typical --rangecheck --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot top_func_impl xil_defaultlib.top xil_defaultlib.glbl -log elaborate.log"
xelab -wto bc7896355b3d4b4caaf88166cc137be7 --incr --debug typical --rangecheck --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot top_func_impl xil_defaultlib.top xil_defaultlib.glbl -log elaborate.log

