#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Mar 10 00:44:09 JST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim top_func_impl -key {Post-Implementation:sim_1:Functional:top} -tclbatch top.tcl -protoinst "protoinst_files/IB_RAM.protoinst" -protoinst "protoinst_files/clock_domain.protoinst" -log simulate.log"
xsim top_func_impl -key {Post-Implementation:sim_1:Functional:top} -tclbatch top.tcl -protoinst "protoinst_files/IB_RAM.protoinst" -protoinst "protoinst_files/clock_domain.protoinst" -log simulate.log

