#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Apr 13 18:03:21 JST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim top_behav -key {Behavioral:sim_1:Functional:top} -tclbatch top.tcl -protoinst "protoinst_files/IB_RAM.protoinst" -protoinst "protoinst_files/clock_domain.protoinst" -view /home/s1820419/LDPC_MinorResearch/GeneratedDecoders/204.33.486/RTL/IB_CNU6_Pipeline_Datapath/top_behav.wcfg -log simulate.log"
xsim top_behav -key {Behavioral:sim_1:Functional:top} -tclbatch top.tcl -protoinst "protoinst_files/IB_RAM.protoinst" -protoinst "protoinst_files/clock_domain.protoinst" -view /home/s1820419/LDPC_MinorResearch/GeneratedDecoders/204.33.486/RTL/IB_CNU6_Pipeline_Datapath/top_behav.wcfg -log simulate.log

