#!/bin/sh
#PBS -N s1820419.Vivado.Sim
#PBS -q SINGLE
#PBS -l select=1
#PBS -j oe

PBS_O_WORKDIR=/home/s1820419/Xilinx/Vivado/project/AXI.UART.customIP/AXI.UART.customIP.sim/sim.7.Jan.2021/xsim
cd ${PBS_O_WORKDIR}

export VIVADOROOT=/home/s1820419/Xilinx/Vivado/2019.2
export PATH="$PATH:$VIVADOROOT/bin"
export VIVADOPATH=$PBS_O_WORKDIR

./entire_ldpc_204_102_sim.sh > sim.log.snr_01_05.txt
