#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Feb 25 22:53:05 JST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim cnu_ib_lut_ram_behav -key {Behavioral:sim_1:Functional:cnu_ib_lut_ram} -tclbatch cnu_ib_lut_ram.tcl -protoinst "protoinst_files/IB_RAM.protoinst" -view /home/s1820419/LDPC_MinorResearch/GeneratedDecoders/204.33.486/RTL/IB_LUT/IB_LUT.sim/sim_1/behav/xsim/cnu_ib_lut_ram_behav.wcfg -log simulate.log"
xsim cnu_ib_lut_ram_behav -key {Behavioral:sim_1:Functional:cnu_ib_lut_ram} -tclbatch cnu_ib_lut_ram.tcl -protoinst "protoinst_files/IB_RAM.protoinst" -view /home/s1820419/LDPC_MinorResearch/GeneratedDecoders/204.33.486/RTL/IB_LUT/IB_LUT.sim/sim_1/behav/xsim/cnu_ib_lut_ram_behav.wcfg -log simulate.log

