# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard.xdc

# Block Designs: bd/IB_RAM/IB_RAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IB_RAM || ORIG_REF_NAME==IB_RAM} -quiet] -quiet

# IP: bd/IB_RAM/ip/IB_RAM_blk_mem_gen_0_0/IB_RAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IB_RAM_blk_mem_gen_0_0 || ORIG_REF_NAME==IB_RAM_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/IB_RAM/IB_RAM_ooc.xdc
