# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sym_lut_struct.xdc

# Block Designs: bd/clock_domain/clock_domain.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_domain || ORIG_REF_NAME==clock_domain} -quiet] -quiet

# IP: bd/clock_domain/ip/clock_domain_clk_wiz_0_0/clock_domain_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_domain_clk_wiz_0_0 || ORIG_REF_NAME==clock_domain_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/clock_domain/clock_domain_ooc.xdc
