# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/zcu104_kit/zcu104_Rev1.0_U1_01302018.xdc

# Block Designs: bd/mem_subsys/mem_subsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_subsys || ORIG_REF_NAME==mem_subsys} -quiet] -quiet

# IP: bd/mem_subsys/ip/mem_subsys_blk_mem_gen_0_0/mem_subsys_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_subsys_blk_mem_gen_0_0 || ORIG_REF_NAME==mem_subsys_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/mem_subsys/mem_subsys_ooc.xdc
